### ISSUE TITLE
Simplify app constructor

### ISSUE THREAD

**Issue by c9s** [go-gas/gas#7]
Right now the gas.New() loads config file implicitly, I think it should be simplified to just new an object.

We can design an app builder to handle config loading or initialization from config file.

```go
app := gas.NewApp()
builder.New(app).loadConfig("config/default.yml")
builder.New(app).load(map[string]string { .... })
```

**Comment by appleboy** [comment]
Fixed via https://github.com/go-gas/gas/commit/e7abee50fb0df0399d8e98b72f0928676a563a4c
